import Head from 'next/head'
import AboutUs from '../../components/AboutUs'
import Carousel from '../../components/Carousel'
import ContactUs from '../../components/ContactUs'
import Hero from '../../components/Hero'
import Navbar from '../../components/Navbar'
import Restaurants from '../../components/Restaurants'
import TodaysOffer from '../../components/TodaysOffers';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-full '>
        <Navbar/>
        <Hero/>
        <Carousel/>
        <div className="bg-black">
        <Restaurants/>
        <TodaysOffer/>
        <ContactUs/>
        <AboutUs/>
        </div>
      </div>
    </>
  )
}
